// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRFvbxCxS2OjB_I2IOnUSM5se7sVqUB3k',
    appId: '1:162817807605:web:00a9869edbbb43cd30e1bc',
    messagingSenderId: '162817807605',
    projectId: 'fooddeliveryapp-7d28d',
    authDomain: 'fooddeliveryapp-7d28d.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-7d28d.firebasestorage.app',
    measurementId: 'G-EKWCTX2ZF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5viT4ez6G4UmIHxlGokRD9NFNd8Uspso',
    appId: '1:162817807605:android:319f318a380f0aec30e1bc',
    messagingSenderId: '162817807605',
    projectId: 'fooddeliveryapp-7d28d',
    storageBucket: 'fooddeliveryapp-7d28d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJO1K-khqIQ_ggY38UXAKX7OoN7tH06Uc',
    appId: '1:162817807605:ios:d56dafcf4dd07fd330e1bc',
    messagingSenderId: '162817807605',
    projectId: 'fooddeliveryapp-7d28d',
    storageBucket: 'fooddeliveryapp-7d28d.firebasestorage.app',
    iosBundleId: 'com.example.frankmichaelflutterproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJO1K-khqIQ_ggY38UXAKX7OoN7tH06Uc',
    appId: '1:162817807605:ios:d56dafcf4dd07fd330e1bc',
    messagingSenderId: '162817807605',
    projectId: 'fooddeliveryapp-7d28d',
    storageBucket: 'fooddeliveryapp-7d28d.firebasestorage.app',
    iosBundleId: 'com.example.frankmichaelflutterproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRFvbxCxS2OjB_I2IOnUSM5se7sVqUB3k',
    appId: '1:162817807605:web:e98d240146c584da30e1bc',
    messagingSenderId: '162817807605',
    projectId: 'fooddeliveryapp-7d28d',
    authDomain: 'fooddeliveryapp-7d28d.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-7d28d.firebasestorage.app',
    measurementId: 'G-R9VQJESS8B',
  );
}
